# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node runtime as the base image
FROM node:16-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json /app/
COPY tsconfig.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the application's source code
COPY . /app

# Build the application
RUN npm run build

# Use a lightweight Node runtime as the release image
FROM node:16-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/dist /app/dist

# Copy package.json and package-lock.json
COPY --from=builder /app/package.json /app/package-lock.json /app/

# Install only production dependencies
RUN npm ci --only=production

# Set environment variables (You need to set these while running the Docker container)
# ENV YOUTUBE_API_KEY=<Your-YouTube-API-Key>
# ENV YOUTUBE_TRANSCRIPT_LANG=en

# Define the command to run the application
CMD ["node", "dist/index.js"]
